/**
 * ~200 historycznych wpisów dziennika Marty — UX designerki, 31 lat.
 * Łuk fabularny: burnout w agencji (2023) → kryzys AI → nowa praca →
 * side project → stabilizacja i dojrzałość (2026).
 *
 * Generowane ręcznie przez Claude do celów demonstracyjnych.
 * Użyj scripts/seed-200.mts żeby wgrać do Supabase.
 */

export interface SeedEntry {
  id: string;
  date: string;
  mood_label: string;
  mood_category: string;
  text: string;
  created_at: string;
  updated_at: string;
}

export const SEED_200: SeedEntry[] = [
  // ─── CZERWIEC 2023 ─────────────────────────────────────────────────────────
  {
    id: "hist-001",
    date: "2023-06-12",
    mood_label: "Reflective",
    mood_category: "Calm",
    text: `<p>Pierwszy wpis. Moja terapeutka powiedziała, żebym spróbowała pisać — że to pomaga poukładać myśli po tym wszystkim co się wydarzyło w agencji. Nie wiem od czego zacząć, więc zacznę od faktów: jestem na L4, mam przy oknie kawę i wreszcie jest cicho. To chyba wystarczy na dziś.</p>`,
    created_at: "2023-06-12T09:14:00.000Z",
    updated_at: "2023-06-12T09:14:00.000Z",
  },
  {
    id: "hist-002",
    date: "2023-06-14",
    mood_label: "Anxious",
    mood_category: "Difficult",
    text: `<p>Obudziłam się o 4 rano z myślą, że zapomniałam wysłać jakiś plik — a przecież już tu nie pracuję. Ten odruch trwa od tygodnia. Siedzę w kuchni, piję herbatę i próbuję powiedzieć sobie, że nie muszę nigdzie biec. Nie bardzo wychodzi.</p>`,
    created_at: "2023-06-14T04:52:00.000Z",
    updated_at: "2023-06-14T04:52:00.000Z",
  },
  {
    id: "hist-003",
    date: "2023-06-17",
    mood_label: "Tired",
    mood_category: "Neutral",
    text: `<p>Długi spacer przez park, dwa odcinki serialu, zero designu. Czuję się jak bateria, która wolno się ładuje. Nie ma w tym nic dramatycznego — po prostu tak teraz jest.</p>`,
    created_at: "2023-06-17T19:30:00.000Z",
    updated_at: "2023-06-17T19:30:00.000Z",
  },
  {
    id: "hist-004",
    date: "2023-06-20",
    mood_label: "Content",
    mood_category: "Positive",
    text: `<p>Zrobiłam coś dla siebie: przeprojektowałam własne CV — nie dlatego, że szukam pracy, ale dlatego że miałam na to ochotę. Spędziłam przy tym trzy godziny i ani razu nie spojrzałam na zegarek. Dawno tak nie było.</p>`,
    created_at: "2023-06-20T15:40:00.000Z",
    updated_at: "2023-06-20T15:40:00.000Z",
  },
  {
    id: "hist-005",
    date: "2023-06-22",
    mood_label: "Focused",
    mood_category: "Calm",
    text: `<p>Wróciłam do Figmy na kilka godzin — projekt dla siebie, bez klienta, bez deadline'u. Projektowałam ekrany aplikacji, która nie istnieje i prawdopodobnie nigdy nie powstanie. I było to fantastyczne. To chyba pierwszy raz od roku, że design sprawił mi przyjemność.</p>`,
    created_at: "2023-06-22T11:20:00.000Z",
    updated_at: "2023-06-22T11:20:00.000Z",
  },
  {
    id: "hist-006",
    date: "2023-06-25",
    mood_label: "Sad",
    mood_category: "Difficult",
    text: `<p>Napisał do mnie Marcin z agencji, że stracili kolejny przetarg. Poczułam mieszaninę winy i ulgi — winy, bo część mnie myśli że porzuciłam ich w złym momencie, ulgi, bo już tam nie jestem. Wieczorem płakałam, nie do końca wiedząc czemu.</p>`,
    created_at: "2023-06-25T21:00:00.000Z",
    updated_at: "2023-06-25T21:00:00.000Z",
  },
  {
    id: "hist-007",
    date: "2023-06-28",
    mood_label: "Relaxed",
    mood_category: "Calm",
    text: `<p>Dzień bez planu — kawiarnia, książka, wieczorem basen. Muszę nauczyć się, że odpoczynek to nie marnowanie czasu. Dzisiaj idzie trochę lepiej.</p>`,
    created_at: "2023-06-28T18:55:00.000Z",
    updated_at: "2023-06-28T18:55:00.000Z",
  },

  // ─── LIPIEC 2023 ───────────────────────────────────────────────────────────
  {
    id: "hist-008",
    date: "2023-07-04",
    mood_label: "Excited",
    mood_category: "Positive",
    text: `<p>Kolega z Twittera wrzucił screeny z Midjourney i szczęka mi opadła. Spędziłam wieczór na generowaniu — wpisywałam opisy interfejsów, postaci, ilustracji i dostawałam coś, co tydzień temu zajęłoby mi dwa dni. Nie wiem co o tym myśleć, ale nie mogłam przestać.</p>`,
    created_at: "2023-07-04T22:10:00.000Z",
    updated_at: "2023-07-04T22:10:00.000Z",
  },
  {
    id: "hist-009",
    date: "2023-07-07",
    mood_label: "Reflective",
    mood_category: "Calm",
    text: `<p>Siedzę i myślę o tym Midjourney. Z jednej strony — absolutna magia. Z drugiej — co to oznacza dla mojego zawodu? Czy za 3 lata ktoś będzie potrzebował designerki? Nie mam odpowiedzi, ale pytanie siedzi w głowie.</p>`,
    created_at: "2023-07-07T20:30:00.000Z",
    updated_at: "2023-07-07T20:30:00.000Z",
  },
  {
    id: "hist-010",
    date: "2023-07-11",
    mood_label: "Content",
    mood_category: "Positive",
    text: `<p>Krótki urlop — jezioro, kajaki, wieczorne grille. Pierwszy raz od bardzo dawna nie myślę o robocie. Dobry znak.</p>`,
    created_at: "2023-07-11T19:00:00.000Z",
    updated_at: "2023-07-11T19:00:00.000Z",
  },
  // [lipiec 14-28 — urlop, brak wpisów]
  {
    id: "hist-011",
    date: "2023-07-30",
    mood_label: "Relaxed",
    mood_category: "Calm",
    text: `<p>Wróciłam z urlopu. Dwa tygodnie bez Figmy, bez Twittera, bez branżowych newsletterów — i czuję się jak inny człowiek. Trochę się boję, że to minie jak wejdę z powrotem w rytm.</p>`,
    created_at: "2023-07-30T17:45:00.000Z",
    updated_at: "2023-07-30T17:45:00.000Z",
  },

  // ─── SIERPIEŃ 2023 ─────────────────────────────────────────────────────────
  {
    id: "hist-012",
    date: "2023-08-03",
    mood_label: "Excited",
    mood_category: "Positive",
    text: `<p>Zainstalowałam ChatGPT Plus i przez całe przedpołudnie pisałam z nim opisy UX copy, tłumaczyłam mikroteksty, testowałam persony. To nie jest zabawka — to realnie przydatne narzędzie. Mój opór topnieje.</p>`,
    created_at: "2023-08-03T12:30:00.000Z",
    updated_at: "2023-08-03T12:30:00.000Z",
  },
  {
    id: "hist-013",
    date: "2023-08-07",
    mood_label: "Anxious",
    mood_category: "Difficult",
    text: `<p>Przeczytałam artykuł: „AI zastąpi 80% pracy grafików w ciągu 5 lat". Siedziałam przy komputerze i czułam jak żołądek mi się ściska. Wiem, że część takich nagłówków to clickbait, ale nie wiem która część. To nieprzyjemne uczucie — pracować w zawodzie i nie wiedzieć, czy ma przyszłość.</p>`,
    created_at: "2023-08-07T18:00:00.000Z",
    updated_at: "2023-08-07T18:00:00.000Z",
  },
  {
    id: "hist-014",
    date: "2023-08-11",
    mood_label: "Focused",
    mood_category: "Calm",
    text: `<p>Postanowiłam nie uciekać od tematu AI, tylko się go nauczyć. Zapisałam się na dwa kursy — prompt engineering i nowe narzędzia dla designerów. Działanie zamiast lęku. Zobaczymy.</p>`,
    created_at: "2023-08-11T10:00:00.000Z",
    updated_at: "2023-08-11T10:00:00.000Z",
  },
  {
    id: "hist-015",
    date: "2023-08-15",
    mood_label: "Indifferent",
    mood_category: "Neutral",
    text: `<p>Płaski dzień. Kurs online, obiad, zakupy. Nic się nie dzieje i jakoś mi to nie przeszkadza — może to właśnie jest normalność, za którą tęskniłam.</p>`,
    created_at: "2023-08-15T20:15:00.000Z",
    updated_at: "2023-08-15T20:15:00.000Z",
  },
  {
    id: "hist-016",
    date: "2023-08-19",
    mood_label: "Frustrated",
    mood_category: "Intense",
    text: `<p>Midjourney wygenerował dokładnie to co chciałam — po trzydziestu próbach i godzinie pisania promptów. Gratulacje, zaoszczędziłam... zero czasu. Czuję frustrację, bo wiem że to kwestia nauki, ale w tej chwili te narzędzia bardziej mnie spowalniają niż pomagają.</p>`,
    created_at: "2023-08-19T16:40:00.000Z",
    updated_at: "2023-08-19T16:40:00.000Z",
  },
  {
    id: "hist-017",
    date: "2023-08-24",
    mood_label: "Tired",
    mood_category: "Neutral",
    text: `<p>Intensywny tydzień kursów. Głowa pełna nowych rzeczy, ale ciało chce tylko kanapę. Jutro biorę dzień wolny od ekranów.</p>`,
    created_at: "2023-08-24T21:30:00.000Z",
    updated_at: "2023-08-24T21:30:00.000Z",
  },
  {
    id: "hist-018",
    date: "2023-08-28",
    mood_label: "Content",
    mood_category: "Positive",
    text: `<p>Mała wygrana: pokazałam Kasi (przyjaciółce, też designerce) jak używam AI do generowania wariantów layoutów. Jej reakcja — niedowierzanie, potem ekscytacja — przypomniała mi jak ja wyglądałam tydzień temu. Fajnie być o krok dalej.</p>`,
    created_at: "2023-08-28T17:00:00.000Z",
    updated_at: "2023-08-28T17:00:00.000Z",
  },

  // ─── WRZESIEŃ 2023 ─────────────────────────────────────────────────────────
  {
    id: "hist-019",
    date: "2023-09-04",
    mood_label: "Focused",
    mood_category: "Calm",
    text: `<p>Zaczęłam szukać pracy na serio. Portfolio aktualizowane, LinkedIn odświeżony, wysłałam pierwsze trzy aplikacje. Dobrze mieć znowu cel — chaos L4 powoli znika.</p>`,
    created_at: "2023-09-04T11:00:00.000Z",
    updated_at: "2023-09-04T11:00:00.000Z",
  },
  {
    id: "hist-020",
    date: "2023-09-08",
    mood_label: "Overwhelmed",
    mood_category: "Intense",
    text: `<p>Pięć rozmów kwalifikacyjnych w jednym tygodniu — każda w innym formacie, inne oczekiwania, inne zadania rekrutacyjne. Wieczorem czułam się jak na karuzeli. Nie wiem czy chcę tej pracy bardziej niż chcę, żeby to się skończyło.</p>`,
    created_at: "2023-09-08T22:00:00.000Z",
    updated_at: "2023-09-08T22:00:00.000Z",
  },
  {
    id: "hist-021",
    date: "2023-09-12",
    mood_label: "Anxious",
    mood_category: "Difficult",
    text: `<p>Dostałam feedback z jednej rekrutacji: „szukamy kogoś z silniejszym skill setem produktowym". Boli. Wiem że mają rację — przez lata byłam bardziej graficzna niż produktowa. Trzeba to nadrobić.</p>`,
    created_at: "2023-09-12T19:30:00.000Z",
    updated_at: "2023-09-12T19:30:00.000Z",
  },
  {
    id: "hist-022",
    date: "2023-09-16",
    mood_label: "Reflective",
    mood_category: "Calm",
    text: `<p>Usiadłam i zrobiłam sobie uczciwy audyt umiejętności — co umiem, czego nie, co chcę umieć za rok. Lista jest długa po obu stronach. To trochę przytłaczające, ale przynajmniej wiem w co celować.</p>`,
    created_at: "2023-09-16T14:00:00.000Z",
    updated_at: "2023-09-16T14:00:00.000Z",
  },
  {
    id: "hist-023",
    date: "2023-09-20",
    mood_label: "Drained",
    mood_category: "Difficult",
    text: `<p>Odrzucona z kolejnej firmy. Tym razem nawet bez feedbacku — po prostu cisza, a potem mail „zdecydowaliśmy się na innego kandydata". Wieczorem nie miałam siły na nic. Tylko serial i herbata.</p>`,
    created_at: "2023-09-20T20:45:00.000Z",
    updated_at: "2023-09-20T20:45:00.000Z",
  },
  {
    id: "hist-024",
    date: "2023-09-25",
    mood_label: "Content",
    mood_category: "Positive",
    text: `<p>Zaproszenie na drugie spotkanie w firmie, która mi się najbardziej podoba. Mały startup, product design od zera — dokładnie to czego potrzebuje moje portfolio. Starałam się nie świętować za wcześnie, ale wieczorem pozwoliłam sobie na lampkę wina.</p>`,
    created_at: "2023-09-25T18:20:00.000Z",
    updated_at: "2023-09-25T18:20:00.000Z",
  },
  {
    id: "hist-025",
    date: "2023-09-28",
    mood_label: "Tired",
    mood_category: "Neutral",
    text: `<p>Zadanie rekrutacyjne zajęło mi cały weekend. Dałam z siebie wszystko, co oznacza że teraz nie mam już nic. Czekam.</p>`,
    created_at: "2023-09-28T23:00:00.000Z",
    updated_at: "2023-09-28T23:00:00.000Z",
  },

  // ─── PAŹDZIERNIK 2023 ──────────────────────────────────────────────────────
  {
    id: "hist-026",
    date: "2023-10-03",
    mood_label: "Reflective",
    mood_category: "Calm",
    text: `<p>Minął tydzień od zadania rekrutacyjnego i ciszy. Postanowiłam nie szaleć z oczekiwaniem i zamiast tego wróciłam do nauki. Skończyłam kurs o systemach projektowania. Przynajmniej coś konkretnego.</p>`,
    created_at: "2023-10-03T16:30:00.000Z",
    updated_at: "2023-10-03T16:30:00.000Z",
  },
  {
    id: "hist-027",
    date: "2023-10-09",
    mood_label: "Frustrated",
    mood_category: "Intense",
    text: `<p>Odrzucona ze startupu. Po tygodniu oczekiwania. Dostałam szczegółowy feedback — doceniam to, ale boli. Mówią że zadanie było dobre, ale na stanowisko szukają kogoś z większym doświadczeniem na poziomie systemowym. Trzecie „prawie" z rzędu.</p>`,
    created_at: "2023-10-09T11:30:00.000Z",
    updated_at: "2023-10-09T11:30:00.000Z",
  },
  {
    id: "hist-028",
    date: "2023-10-13",
    mood_label: "Drained",
    mood_category: "Difficult",
    text: `<p>Wzięłam kilka dni przerwy od poszukiwania pracy. Czuję się wyczerpana tym procesem — każda rekrutacja to mini-projekt, a mini-projekty się kumulują. Muszę znaleźć coś tymczasowego, zanim skończy się poduszka finansowa.</p>`,
    created_at: "2023-10-13T14:00:00.000Z",
    updated_at: "2023-10-13T14:00:00.000Z",
  },
  {
    id: "hist-029",
    date: "2023-10-17",
    mood_label: "Focused",
    mood_category: "Calm",
    text: `<p>Nowy plan: biorę dwa zlecenia freelancerskie na resztę roku — mniejsze pieniądze, ale zero presji rekrutacyjnej. Jednocześnie buduję case study, które pokazuje to czego mi brakowało w poprzednich procesach. Działam.</p>`,
    created_at: "2023-10-17T10:00:00.000Z",
    updated_at: "2023-10-17T10:00:00.000Z",
  },
  {
    id: "hist-030",
    date: "2023-10-23",
    mood_label: "Excited",
    mood_category: "Positive",
    text: `<p>Pierwsze zlecenie freelancerskie — redesign aplikacji dla małej firmy logistycznej. Brzmi nudno, ale klient jest miły, brief jasny, a ja po raz pierwszy od miesięcy mam coś konkretnego do zrobienia. Czuję się prawie jak dawniej.</p>`,
    created_at: "2023-10-23T09:30:00.000Z",
    updated_at: "2023-10-23T09:30:00.000Z",
  },
  {
    id: "hist-031",
    date: "2023-10-28",
    mood_label: "Indifferent",
    mood_category: "Neutral",
    text: `<p>Środkowa faza projektu: wireframes zrobione, czekam na feedback. Te martwe punkty między iteracjami zawsze mnie trochę dołują. Oglądam konferencje z branży AI i jestem coraz bardziej przekonana, że za rok połowa moich narzędzi będzie wyglądać inaczej.</p>`,
    created_at: "2023-10-28T19:00:00.000Z",
    updated_at: "2023-10-28T19:00:00.000Z",
  },

  // ─── LISTOPAD 2023 ─────────────────────────────────────────────────────────
  {
    id: "hist-032",
    date: "2023-11-03",
    mood_label: "Content",
    mood_category: "Positive",
    text: `<p>Prezentacja finalnych makiet — klient zachwycony. Pierwsze słowa: „to jest dokładnie to, co miałem w głowie, ale nie umiałem opisać". Najlepsza rzecz jaką designer może usłyszeć. Wieczorem świętowałam z Kasią.</p>`,
    created_at: "2023-11-03T20:00:00.000Z",
    updated_at: "2023-11-03T20:00:00.000Z",
  },
  {
    id: "hist-033",
    date: "2023-11-08",
    mood_label: "Focused",
    mood_category: "Calm",
    text: `<p>Nowe case study gotowe — przepisałam całą narrację pod kątem product thinking. Widać progres w stosunku do starych projektów. Wysyłam do kilku firm które mnie interesują, zanim oficjalnie otworzą rekrutacje.</p>`,
    created_at: "2023-11-08T14:30:00.000Z",
    updated_at: "2023-11-08T14:30:00.000Z",
  },
  {
    id: "hist-034",
    date: "2023-11-13",
    mood_label: "Overwhelmed",
    mood_category: "Intense",
    text: `<p>Dawna agencja zadzwoniła z prośbą o pomoc przy projekcie — nagły, pilny, zapłacą dobrze. Głupio odmówić, ale wiem że to oznacza tydzień chaosu. Powiedziałam tak i już tego żałuję. Znowu dałam się wciągnąć w stary schemat.</p>`,
    created_at: "2023-11-13T17:00:00.000Z",
    updated_at: "2023-11-13T17:00:00.000Z",
  },
  {
    id: "hist-035",
    date: "2023-11-18",
    mood_label: "Drained",
    mood_category: "Difficult",
    text: `<p>Projekt dla agencji skończony, ale zostałam z poczuciem że znowu pozwoliłam się wyeksploatować. Pieniądze wpłynęły, ale kosztem były cztery nieprzespane noce. Muszę nauczyć się mówić nie — podobno to proste, w praktyce wciąż mi nie wychodzi.</p>`,
    created_at: "2023-11-18T22:30:00.000Z",
    updated_at: "2023-11-18T22:30:00.000Z",
  },
  {
    id: "hist-036",
    date: "2023-11-24",
    mood_label: "Sad",
    mood_category: "Difficult",
    text: `<p>Listopada coraz więcej ciemności — dosłownie i w przenośni. Brakuje mi stałości: stałego miejsca pracy, stałych ludzi, stałego rytmu. Freelancing jest wolny, ale też trochę samotny.</p>`,
    created_at: "2023-11-24T18:00:00.000Z",
    updated_at: "2023-11-24T18:00:00.000Z",
  },
  {
    id: "hist-037",
    date: "2023-11-29",
    mood_label: "Reflective",
    mood_category: "Calm",
    text: `<p>Pół roku od odejścia z agencji. Zrobiłam bilans: lepiej śpię, mniej boli mnie głowa, nauczyłam się trzech nowych narzędzi, zrobiłam dwa udane projekty freelancerskie. Minus: brak struktury i trochę za dużo czasu samej ze sobą. Niezły bilans jak na sześć miesięcy.</p>`,
    created_at: "2023-11-29T20:00:00.000Z",
    updated_at: "2023-11-29T20:00:00.000Z",
  },

  // ─── GRUDZIEŃ 2023 ─────────────────────────────────────────────────────────
  // [1-19 grudnia — cisza, wyciszenie, mała depresja sezonowa]
  {
    id: "hist-038",
    date: "2023-12-20",
    mood_label: "Relaxed",
    mood_category: "Calm",
    text: `<p>Wyjechałam do rodziców na Święta wcześniej niż zwykle. Dom, znajome zapachy, mama gotuje bigos. Odkładam telefon na dwie godziny i siedzę przy stole z herbatą. Nie pamiętam kiedy ostatnio czułam się tak bezpiecznie.</p>`,
    created_at: "2023-12-20T16:00:00.000Z",
    updated_at: "2023-12-20T16:00:00.000Z",
  },
  {
    id: "hist-039",
    date: "2023-12-24",
    mood_label: "Joyful",
    mood_category: "Positive",
    text: `<p>Wigilia — cały dom, całe zamieszanie. Małe bratanice biegają i krzyczą a ja siedzę i myślę że to chyba właśnie o to chodzi. Nie o design systems ani o AI — o ludzi przy stole. Dobry wieczór.</p>`,
    created_at: "2023-12-24T21:30:00.000Z",
    updated_at: "2023-12-24T21:30:00.000Z",
  },
  {
    id: "hist-040",
    date: "2023-12-28",
    mood_label: "Content",
    mood_category: "Positive",
    text: `<p>Leniwe dni między Świętami a Nowym Rokiem. Zaczęłam czytać książkę o psychologii kreatywności — pierwszy raz od lat czytam coś niezwiązanego z pracą dla czystej przyjemności. Polecam ten stan.</p>`,
    created_at: "2023-12-28T14:00:00.000Z",
    updated_at: "2023-12-28T14:00:00.000Z",
  },
  {
    id: "hist-041",
    date: "2023-12-31",
    mood_label: "Reflective",
    mood_category: "Calm",
    text: `<p>Ostatni dzień roku. 2023 był ciężki i potrzebny — burnout, leczenie, reset. Nauczyłam się że moje granice są prawdziwe i że ich pilnowanie nie jest egoizmem. Na 2024 chcę jednej rzeczy: pracy, która mi nie odbiera siebie.</p>`,
    created_at: "2023-12-31T23:00:00.000Z",
    updated_at: "2023-12-31T23:00:00.000Z",
  },

  // ─── STYCZEŃ 2024 ──────────────────────────────────────────────────────────
  {
    id: "hist-042",
    date: "2024-01-04",
    mood_label: "Anxious",
    mood_category: "Difficult",
    text: `<p>Nowy rok, nowa rekrutacja. Dostałam wiadomość od headhunterki — startup fintech szuka senior product designerki. Poczułam równocześnie ekscytację i strach. Wyślę CV, ale tym razem bez stawiania wszystkiego na jedną kartę.</p>`,
    created_at: "2024-01-04T10:00:00.000Z",
    updated_at: "2024-01-04T10:00:00.000Z",
  },
  {
    id: "hist-043",
    date: "2024-01-10",
    mood_label: "Focused",
    mood_category: "Calm",
    text: `<p>Pierwsze rozmowy kwalifikacyjne w nowym roku. Przygotowałam się lepiej niż kiedykolwiek — zrobiłam research o firmie, przećwiczyłam opowiadanie case studies, miałam gotowe pytania. Coś w tym jest: przygotowanie naprawdę zmniejsza lęk.</p>`,
    created_at: "2024-01-10T19:30:00.000Z",
    updated_at: "2024-01-10T19:30:00.000Z",
  },
  {
    id: "hist-044",
    date: "2024-01-15",
    mood_label: "Excited",
    mood_category: "Positive",
    text: `<p>Drugie spotkanie z fintechem i tym razem z całym zespołem produktowym. Czuję chemistry — lead PM mówi tak jak ja myślę, zadają pytania które mnie interesują, a nie tylko testują wiedzę encyklopedyczną. Jestem ostrożnie optymistyczna.</p>`,
    created_at: "2024-01-15T18:00:00.000Z",
    updated_at: "2024-01-15T18:00:00.000Z",
  },
  {
    id: "hist-045",
    date: "2024-01-20",
    mood_label: "Bored",
    mood_category: "Neutral",
    text: `<p>Znowu czekam. Rekrutacje mają to do siebie że są albo intensywne albo martwe. Ten tydzień to martwica — jedno małe zlecenie, dużo kawy, trochę nauki. Staram się nie myśleć za dużo o ofercie.</p>`,
    created_at: "2024-01-20T15:00:00.000Z",
    updated_at: "2024-01-20T15:00:00.000Z",
  },
  {
    id: "hist-046",
    date: "2024-01-25",
    mood_label: "Reflective",
    mood_category: "Calm",
    text: `<p>Rozmawiam z terapeutką o lęku przed sukcesem. Zaskakujące odkrycie: part of me sabotuje aplikacje, bo boję się że dostanę pracę i znowu się wypalę. Nad tym trzeba popracować.</p>`,
    created_at: "2024-01-25T17:30:00.000Z",
    updated_at: "2024-01-25T17:30:00.000Z",
  },
  {
    id: "hist-047",
    date: "2024-01-30",
    mood_label: "Joyful",
    mood_category: "Positive",
    text: `<p>Dostałam ofertę. Fintech, senior product designer, normalny tryb pracy, hybryda. Płakałam z ulgi przy telefonie z mamą — co trochę mnie zaskoczyło, bo myślałam że już nie będę tak reagować. Zaczynam 12 lutego.</p>`,
    created_at: "2024-01-30T14:30:00.000Z",
    updated_at: "2024-01-30T14:30:00.000Z",
  },

  // ─── LUTY 2024 ─────────────────────────────────────────────────────────────
  {
    id: "hist-048",
    date: "2024-02-06",
    mood_label: "Excited",
    mood_category: "Positive",
    text: `<p>Pierwszy tydzień w Kolibri (tak się nazywa ta firma). Trochę overwhelming — nowy stack narzędzi, nowe procesy, dziesięć nowych twarzy — ale w dobrym sensie. Czuję że trafiłam na zespół który serio myśli o produkcie. Wieczorem wróciłam do domu z energią, nie z wypaleniem.</p>`,
    created_at: "2024-02-06T20:00:00.000Z",
    updated_at: "2024-02-06T20:00:00.000Z",
  },
  {
    id: "hist-049",
    date: "2024-02-13",
    mood_label: "Tired",
    mood_category: "Neutral",
    text: `<p>Drugi tydzień. Onboarding to maraton — dużo słuchania, czytania dokumentów, zadawania pytań. Mózg prosi o przerwę. Muszę pamiętać że to normalne i że nie muszę wszystkiego wiedzieć od razu.</p>`,
    created_at: "2024-02-13T21:00:00.000Z",
    updated_at: "2024-02-13T21:00:00.000Z",
  },
  {
    id: "hist-050",
    date: "2024-02-19",
    mood_label: "Focused",
    mood_category: "Calm",
    text: `<p>Dostałam pierwszy prawdziwy projekt — redesign flow onboardingu dla nowych użytkowników. Dokładnie ta skala i złożoność, w której lubię pracować. Zrobiłam audyt obecnego stanu i już widzę pięć rzeczy które można poprawić. Dobry start.</p>`,
    created_at: "2024-02-19T16:00:00.000Z",
    updated_at: "2024-02-19T16:00:00.000Z",
  },
  {
    id: "hist-051",
    date: "2024-02-24",
    mood_label: "Overwhelmed",
    mood_category: "Intense",
    text: `<p>Nagle okazało się że do onboardingu jest też feedback od CEO, badania od PM-a, i zaległe zadania od poprzedniej designerki których nikt mi nie przekazał. Trzy tygodnie po starcie i już czuję znajomy ucisk w klatce. Oddech. To tylko projekt, nie całe życie.</p>`,
    created_at: "2024-02-24T18:30:00.000Z",
    updated_at: "2024-02-24T18:30:00.000Z",
  },
  {
    id: "hist-052",
    date: "2024-02-29",
    mood_label: "Reflective",
    mood_category: "Calm",
    text: `<p>Przestawek roku: 29 lutego — dzień który pojawia się raz na cztery lata. Symbolicznie czysty, niezapisany. Wieczorem zrobiłam retrospektywę pierwszych trzech tygodni: za szybko biorę na siebie cudze zadania, za wolno mówię o swoich ograniczeniach. Na to trzeba uważać.</p>`,
    created_at: "2024-02-29T22:00:00.000Z",
    updated_at: "2024-02-29T22:00:00.000Z",
  },

  // ─── MARZEC 2024 ───────────────────────────────────────────────────────────
  {
    id: "hist-053",
    date: "2024-03-04",
    mood_label: "Focused",
    mood_category: "Calm",
    text: `<p>Zaczęłam systematycznie dokumentować decyzje projektowe w Notion — kto powiedział co, dlaczego wybrałam takie rozwiązanie, co odrzuciłam i dlaczego. Trochę więcej pracy, ale chcę żebyśmy mieli memory jako zespół, nie tylko ja. Lead PM powiedział że to dobry pomysł.</p>`,
    created_at: "2024-03-04T11:00:00.000Z",
    updated_at: "2024-03-04T11:00:00.000Z",
  },
  {
    id: "hist-054",
    date: "2024-03-08",
    mood_label: "Content",
    mood_category: "Positive",
    text: `<p>Pierwsze testy użytkowników z nowym flow — pięć osób, trzy godziny nagrań. Jedno odkrycie natychmiast wylądowało w designie. To właśnie lubię w produkcie: feedback jest szybki i konkretny, nie przepada gdzieś w procesie agencyjnym.</p>`,
    created_at: "2024-03-08T17:30:00.000Z",
    updated_at: "2024-03-08T17:30:00.000Z",
  },
  {
    id: "hist-055",
    date: "2024-03-13",
    mood_label: "Anxious",
    mood_category: "Difficult",
    text: `<p>Na firmowym Slacku pojawił się kanał #ai-tools. Ktoś linkuje Galileo AI, ktoś inny testuje Figma AI. Część mnie jest ciekawa, część czuje ten stary lęk — „czy zaraz się okaże że połowa mojej pracy jest zbędna?". Muszę z tym usiąść.</p>`,
    created_at: "2024-03-13T19:00:00.000Z",
    updated_at: "2024-03-13T19:00:00.000Z",
  },
  {
    id: "hist-056",
    date: "2024-03-18",
    mood_label: "Focused",
    mood_category: "Calm",
    text: `<p>Przetestowałam Galileo AI przez tydzień. Wynik: przydatne do szybkiego prototypowania struktury, ale wyniki są generyczne i wymagają dużej korekty. Nie jestem zagrożona — jestem wzbogacona o nowe narzędzie. Lęk opada o kilka stopni.</p>`,
    created_at: "2024-03-18T14:00:00.000Z",
    updated_at: "2024-03-18T14:00:00.000Z",
  },
  {
    id: "hist-057",
    date: "2024-03-22",
    mood_label: "Joyful",
    mood_category: "Positive",
    text: `<p>Nasz nowy onboarding wszedł na produkcję. Conversion w pierwszym tygodniu +18%. Przy spotkaniu całego zespołu ktoś powiedział „to jest dokładnie ta poprawa której potrzebowaliśmy" — i poczułam coś, czego dawno w pracy nie czułam: dumę bez strachu.</p>`,
    created_at: "2024-03-22T16:30:00.000Z",
    updated_at: "2024-03-22T16:30:00.000Z",
  },
  {
    id: "hist-058",
    date: "2024-03-27",
    mood_label: "Tired",
    mood_category: "Neutral",
    text: `<p>Sprint zakończony, nowy sprint zaczęty. Trochę jak hamster w kole, ale przynajmniej nasze koło idzie gdzieś. Wieczór dla siebie — długa kąpiel, nic do roboty.</p>`,
    created_at: "2024-03-27T21:30:00.000Z",
    updated_at: "2024-03-27T21:30:00.000Z",
  },

  // ─── KWIECIEŃ 2024 ─────────────────────────────────────────────────────────
  {
    id: "hist-059",
    date: "2024-04-03",
    mood_label: "Reflective",
    mood_category: "Calm",
    text: `<p>Spotkanie 1:1 z szefem — powiedział że jest zadowolony z mojej pracy i widzi mój wkład w kulturę dokumentowania decyzji. Poczułam jak zsuwa mi się z barków coś, o czym nie wiedziałam że dźwigam. Potrzebowałam tej informacji zwrotnej.</p>`,
    created_at: "2024-04-03T12:00:00.000Z",
    updated_at: "2024-04-03T12:00:00.000Z",
  },
  {
    id: "hist-060",
    date: "2024-04-09",
    mood_label: "Excited",
    mood_category: "Positive",
    text: `<p>Dostałam zaproszenie do Design Systems Working Group — mały cross-team team który ma ujednolicić komponenty w całym produkcie. To dokładnie ta robota, której mi brakowało w poprzednich firmach. Nie mogę się doczekać.</p>`,
    created_at: "2024-04-09T10:30:00.000Z",
    updated_at: "2024-04-09T10:30:00.000Z",
  },
  {
    id: "hist-061",
    date: "2024-04-14",
    mood_label: "Frustrated",
    mood_category: "Intense",
    text: `<p>Pierwsze spotkanie Design Systems WG — pół godziny o tym kto ma uprawnienia do edycji pliku w Figmie. To mnie dobija w pracy korporacyjnej: zanim zaczniesz działać, przeprawiasz się przez góry procedur. Mam nadzieję że to nie będzie norma.</p>`,
    created_at: "2024-04-14T17:00:00.000Z",
    updated_at: "2024-04-14T17:00:00.000Z",
  },
  {
    id: "hist-062",
    date: "2024-04-19",
    mood_label: "Indifferent",
    mood_category: "Neutral",
    text: `<p>Piątek, nieznaczący tydzień za mną. Nie było ani dobrze ani źle — po prostu praca, posiłki, sen. Czasem taka banalność jest w porządku.</p>`,
    created_at: "2024-04-19T18:00:00.000Z",
    updated_at: "2024-04-19T18:00:00.000Z",
  },
  {
    id: "hist-063",
    date: "2024-04-24",
    mood_label: "Focused",
    mood_category: "Calm",
    text: `<p>Zaczęłam pracę nad design tokenami dla naszego systemu — spacing, typografia, kolory. Żmudna, ale satysfakcjonująca robota. Wiem że za rok ktoś będzie mi wdzięczny za te godziny. Może nawet ja sama.</p>`,
    created_at: "2024-04-24T15:00:00.000Z",
    updated_at: "2024-04-24T15:00:00.000Z",
  },
  {
    id: "hist-064",
    date: "2024-04-29",
    mood_label: "Relaxed",
    mood_category: "Calm",
    text: `<p>Długi weekend majowy. Wyjazd z Kasią do Wrocławia — kawiarnie, galeria, dużo chodzenia. Nie rozmawiałyśmy prawie wcale o pracy. Tak powinno być.</p>`,
    created_at: "2024-04-29T22:00:00.000Z",
    updated_at: "2024-04-29T22:00:00.000Z",
  },

  // ─── MAJ 2024 ──────────────────────────────────────────────────────────────
  {
    id: "hist-065",
    date: "2024-05-07",
    mood_label: "Content",
    mood_category: "Positive",
    text: `<p>Trzy miesiące w Kolibri. Czuję się jak stały element zespołu — nie gość. Nowi developerzy pytają mnie o komponenty, PM przychodzi po radę w kwestiach UX. To buduje.</p>`,
    created_at: "2024-05-07T11:00:00.000Z",
    updated_at: "2024-05-07T11:00:00.000Z",
  },
  {
    id: "hist-066",
    date: "2024-05-13",
    mood_label: "Anxious",
    mood_category: "Difficult",
    text: `<p>OpenAI ogłosiło GPT-4o — demo z prawdziwą rozmową głosową i analizą obrazu w czasie rzeczywistym. Siedzę z otwartą szczęką i nie wiem co czuję. Ekscytacja? Zagrożenie? To coraz trudniej rozgraniczyć.</p>`,
    created_at: "2024-05-13T22:00:00.000Z",
    updated_at: "2024-05-13T22:00:00.000Z",
  },
  {
    id: "hist-067",
    date: "2024-05-17",
    mood_label: "Reflective",
    mood_category: "Calm",
    text: `<p>Rozmowa z Łukaszem (developer w zespole) o GPT-4o. On mówi że to narzędzie, ja słyszę że to zmiana paradygmatu. Może oboje mamy rację. Przynajmniej mówimy o tym otwarcie zamiast chować głowę w piasek.</p>`,
    created_at: "2024-05-17T16:00:00.000Z",
    updated_at: "2024-05-17T16:00:00.000Z",
  },
  {
    id: "hist-068",
    date: "2024-05-22",
    mood_label: "Tired",
    mood_category: "Neutral",
    text: `<p>Pięć spotkań w jeden dzień. Wróciłam do domu z mózgiem-papką. To jedna z rzeczy której nie lubię w produkcie: ciągłe calibrowanie z każdym. Jutro blokuję sobie rano na fokus.</p>`,
    created_at: "2024-05-22T20:00:00.000Z",
    updated_at: "2024-05-22T20:00:00.000Z",
  },
  {
    id: "hist-069",
    date: "2024-05-27",
    mood_label: "Focused",
    mood_category: "Calm",
    text: `<p>Nowy projekt: redesign dashboard dla zaawansowanych użytkowników. Zaczęłam od tygodnia wywiadów — nic nie projektuję, tylko słucham. Stary ja by już był w Figmie. Progres.</p>`,
    created_at: "2024-05-27T14:30:00.000Z",
    updated_at: "2024-05-27T14:30:00.000Z",
  },

  // ─── CZERWIEC 2024 ─────────────────────────────────────────────────────────
  {
    id: "hist-070",
    date: "2024-06-04",
    mood_label: "Drained",
    mood_category: "Difficult",
    text: `<p>Cztery miesiące intensywnej pracy bez prawdziwego oddechu. Zaczęłam zauważać sygnały — poranne zmęczenie zanim wstanę, irytacja przy Slacku, brak entuzjazmu który miałam w lutym. Nie chcę znowu dojść do ściany. Muszę zadziałać wcześniej tym razem.</p>`,
    created_at: "2024-06-04T19:00:00.000Z",
    updated_at: "2024-06-04T19:00:00.000Z",
  },
  {
    id: "hist-071",
    date: "2024-06-10",
    mood_label: "Anxious",
    mood_category: "Difficult",
    text: `<p>Przeczytałam długi wątek na Twitterze: designerzy zwolnieni w startupach zastąpieni przez AI plus jednego juniora z promptami. Wiem że to anegdoty, ale siedzę z tym i mam ściśnięty żołądek. Muszę z tym porozmawiać — z terapeutką albo z kimś bliskim.</p>`,
    created_at: "2024-06-10T21:30:00.000Z",
    updated_at: "2024-06-10T21:30:00.000Z",
  },
  {
    id: "hist-072",
    date: "2024-06-15",
    mood_label: "Reflective",
    mood_category: "Calm",
    text: `<p>Wróciłam do terapii — tym razem nie z kryzysem, ale prewencyjnie. Opowiedziałam o lęku przed AI i o tym co czuję czytając te wszystkie artykuły. Terapeutka zapytała: „a co konkretnie straciłabyś, gdyby AI przejął część twojej pracy?". Dobre pytanie. Nie mam odpowiedzi.</p>`,
    created_at: "2024-06-15T17:00:00.000Z",
    updated_at: "2024-06-15T17:00:00.000Z",
  },
  {
    id: "hist-073",
    date: "2024-06-21",
    mood_label: "Sad",
    mood_category: "Difficult",
    text: `<p>Długa rozmowa z Kasią — ona też ma te lęki, też zastanawia się czy jej zawód ma przyszłość. Ulga że nie jestem sama, ale też smutek że obydwie się z tym zmagamy. Skończyłyśmy wieczór na winie i starym albumie ze studiów. Lepiej.</p>`,
    created_at: "2024-06-21T23:00:00.000Z",
    updated_at: "2024-06-21T23:00:00.000Z",
  },
  {
    id: "hist-074",
    date: "2024-06-28",
    mood_label: "Content",
    mood_category: "Positive",
    text: `<p>Dostałam pozytywny feedback od szefa za dashboard projekt — mówi że moja metoda badań uczyniła z projektu prawdziwy produkt, nie tylko ładny interfejs. Poczułam jak ta stara pewność siebie powoli wraca. AI nie zrobiłoby tych rozmów z użytkownikami.</p>`,
    created_at: "2024-06-28T16:30:00.000Z",
    updated_at: "2024-06-28T16:30:00.000Z",
  },

  // ─── LIPIEC 2024 ───────────────────────────────────────────────────────────
  // [lipiec 1-19 — urlop letni, brak wpisów]
  {
    id: "hist-075",
    date: "2024-07-20",
    mood_label: "Relaxed",
    mood_category: "Calm",
    text: `<p>Trzy tygodnie na Sardynii — morze, włoskie kolacje, zero Figmy. Wróciłam z nową energią i z przekonaniem, że przerwy od pracy to nie luksus, to konieczność. Czemu musiałam się tego uczyć dwa razy?</p>`,
    created_at: "2024-07-20T18:00:00.000Z",
    updated_at: "2024-07-20T18:00:00.000Z",
  },
  {
    id: "hist-076",
    date: "2024-07-26",
    mood_label: "Focused",
    mood_category: "Calm",
    text: `<p>Powrót do biura po urlopie — zamiast rzucać się na backlog, wzięłam jeden dzień na przegląd co się zmieniło w moją nieobecność. Stara ja zaczęłaby od dołu listy zadań i trybu pożarowego. Nowa ja najpierw rozumie, potem działa.</p>`,
    created_at: "2024-07-26T16:00:00.000Z",
    updated_at: "2024-07-26T16:00:00.000Z",
  },

  // ─── SIERPIEŃ 2024 ─────────────────────────────────────────────────────────
  {
    id: "hist-077",
    date: "2024-08-06",
    mood_label: "Reflective",
    mood_category: "Calm",
    text: `<p>Na terapii rozmawiałyśmy o pytaniu sprzed dwóch miesięcy: „co straciłabyś?". Doszłam do odpowiedzi: nie obawiam się utraty narzędzi — obawiam się utraty tożsamości. „Jestem designerką" to dużo więcej niż zestaw umiejętności. To mój sposób patrzenia na świat.</p>`,
    created_at: "2024-08-06T20:00:00.000Z",
    updated_at: "2024-08-06T20:00:00.000Z",
  },
  {
    id: "hist-078",
    date: "2024-08-12",
    mood_label: "Excited",
    mood_category: "Positive",
    text: `<p>Coś kliknęło — zaczęłam używać Claude do rozmów o problemach projektowych. Nie jako automat do generowania makiet, ale jako rozmówcę który zadaje dobre pytania. To całkiem inne doświadczenie niż prompt-and-generate. Czuję się jak mam myślącego partnera do burzy mózgów.</p>`,
    created_at: "2024-08-12T14:00:00.000Z",
    updated_at: "2024-08-12T14:00:00.000Z",
  },
  {
    id: "hist-079",
    date: "2024-08-17",
    mood_label: "Focused",
    mood_category: "Calm",
    text: `<p>Tydzień eksperymentowania: AI do research synthesis, AI do tworzenia scenariuszy testów, AI do pierwszego draftu copy. Moja rola: oceniać, odrzucać, kierunkować, integrować. To trochę jak bycie art directorem zamiast wykonawcą. Mi to pasuje.</p>`,
    created_at: "2024-08-17T11:00:00.000Z",
    updated_at: "2024-08-17T11:00:00.000Z",
  },
  {
    id: "hist-080",
    date: "2024-08-22",
    mood_label: "Indifferent",
    mood_category: "Neutral",
    text: `<p>Środa. Normalna. Praca, lunch, spacer, praca. Nic szczególnego. Wcześniej takie dni mnie denerwowały brakiem „postępu" — teraz myślę że to po prostu stabilność. Nie każdy dzień musi być przełomowy.</p>`,
    created_at: "2024-08-22T19:30:00.000Z",
    updated_at: "2024-08-22T19:30:00.000Z",
  },
  {
    id: "hist-081",
    date: "2024-08-27",
    mood_label: "Content",
    mood_category: "Positive",
    text: `<p>Pokazałam zespołowi mój AI-assisted workflow na retrospekcji. Reakcje były mieszane — sceptycyzm, ciekawość, jedno „to brzmi jak zastępowanie designerów". Miałam gotową odpowiedź: to zastępuje godziny na powtarzalnych zadaniach, nie myślenie. Chyba przekonałam połowę sali.</p>`,
    created_at: "2024-08-27T17:00:00.000Z",
    updated_at: "2024-08-27T17:00:00.000Z",
  },

  // ─── WRZESIEŃ 2024 ─────────────────────────────────────────────────────────
  {
    id: "hist-082",
    date: "2024-09-03",
    mood_label: "Excited",
    mood_category: "Positive",
    text: `<p>Mam pomysł na side project — aplikacja która pomaga designerom używać AI w procesie badań użytkowników. Widzę wyraźną lukę: narzędzia albo są zbyt generyczne, albo zbyt techniczne. Coś pomiędzy mógłby być mój product. Zaczynam szkicować.</p>`,
    created_at: "2024-09-03T21:00:00.000Z",
    updated_at: "2024-09-03T21:00:00.000Z",
  },
  {
    id: "hist-083",
    date: "2024-09-09",
    mood_label: "Focused",
    mood_category: "Calm",
    text: `<p>Porozmawiałam z siedmioma designerami o ich frustracjach z AI. Trzy wspólne motywy: za dużo kontekstu do przekazania za każdym razem, wyniki zbyt generyczne, brak integracji z ich realnym workflow. To konkretny problem. To dobry znak na start.</p>`,
    created_at: "2024-09-09T14:00:00.000Z",
    updated_at: "2024-09-09T14:00:00.000Z",
  },
  {
    id: "hist-084",
    date: "2024-09-15",
    mood_label: "Tired",
    mood_category: "Neutral",
    text: `<p>Praca w dzień plus side project wieczorami to zmęczające połączenie. Muszę być bardziej zdyscyplinowana z czasem — albo side project, albo wieczorny Netflix, nie oba. Na razie wychodzi tak że mam ani jedno ani drugie, tylko zmęczenie.</p>`,
    created_at: "2024-09-15T22:00:00.000Z",
    updated_at: "2024-09-15T22:00:00.000Z",
  },
  {
    id: "hist-085",
    date: "2024-09-21",
    mood_label: "Reflective",
    mood_category: "Calm",
    text: `<p>Rok minął od tamtego trudnego września z rekrutacjami. Wtedy czułam się jak osoba bez kierunku, teraz — jak osoba z za dużą liczbą kierunków. Oba stany mają swoje problemy, ale wolę ten drugi.</p>`,
    created_at: "2024-09-21T18:30:00.000Z",
    updated_at: "2024-09-21T18:30:00.000Z",
  },
  {
    id: "hist-086",
    date: "2024-09-26",
    mood_label: "Joyful",
    mood_category: "Positive",
    text: `<p>Pokazałam pierwsze mockupy side projektu Kasi i Łukaszowi — oboje powiedzieli że to coś czego potrzebują. Łukasz zaproponował że pomoże z backendem. Mały team, duża energia. Nazwy jeszcze nie ma, ale projekt istnieje.</p>`,
    created_at: "2024-09-26T20:00:00.000Z",
    updated_at: "2024-09-26T20:00:00.000Z",
  },

  // ─── PAŹDZIERNIK 2024 ──────────────────────────────────────────────────────
  {
    id: "hist-087",
    date: "2024-10-04",
    mood_label: "Focused",
    mood_category: "Calm",
    text: `<p>Pierwsze spotkanie z Łukaszem o side projekcie — tech stack, timeline, zakres. Zdecydowałyśmy się zacząć małO: MVP z jedną funkcją doprowadzoną do perfekcji zamiast dziesięciu niedoróbek. To wbrew moim starym nawykom. Dobrze.</p>`,
    created_at: "2024-10-04T15:00:00.000Z",
    updated_at: "2024-10-04T15:00:00.000Z",
  },
  {
    id: "hist-088",
    date: "2024-10-10",
    mood_label: "Indifferent",
    mood_category: "Neutral",
    text: `<p>Środek tygodnia, środek projektu, środek miesiąca. Nic szczególnego do odnotowania. Może to właśnie jest dojrzałość — że nie każdy dzień musi być zaznaczony flamastrem.</p>`,
    created_at: "2024-10-10T20:00:00.000Z",
    updated_at: "2024-10-10T20:00:00.000Z",
  },
  {
    id: "hist-089",
    date: "2024-10-17",
    mood_label: "Anxious",
    mood_category: "Difficult",
    text: `<p>Duże ogłoszenie w branży: kolejna platforma designerska zintegrowana z AI, zapowiedzi że za rok będą „end-to-end AI design flow". Jak zawsze po takich newsach muszę odpocząć od Twittera bo wpadam w spiralę. Godzina bez telefonu, spacer. Lepiej.</p>`,
    created_at: "2024-10-17T18:00:00.000Z",
    updated_at: "2024-10-17T18:00:00.000Z",
  },
  {
    id: "hist-090",
    date: "2024-10-22",
    mood_label: "Content",
    mood_category: "Positive",
    text: `<p>Mały przełom w side projekcie — zintegrowaliśmy z Łukaszem API i pierwszy raz zobaczyłam żyjące dane w moim interfejsie. To zawsze robi różnicę: mockup to mockup, ale działający produkt ma zupełnie inną energię. Wieczorem byliśmy bardzo z siebie dumni.</p>`,
    created_at: "2024-10-22T21:30:00.000Z",
    updated_at: "2024-10-22T21:30:00.000Z",
  },
  {
    id: "hist-091",
    date: "2024-10-28",
    mood_label: "Reflective",
    mood_category: "Calm",
    text: `<p>Rok temu bałam się AI. Teraz buduję produkt który go używa. Jak to się stało? Myślę że kluczowe było przejście od pytania „czy mnie zastąpi" do pytania „jak mogę z tym pracować". Zmiana framu wszystko zmienia.</p>`,
    created_at: "2024-10-28T20:00:00.000Z",
    updated_at: "2024-10-28T20:00:00.000Z",
  },

  // ─── LISTOPAD 2024 ─────────────────────────────────────────────────────────
  {
    id: "hist-092",
    date: "2024-11-05",
    mood_label: "Excited",
    mood_category: "Positive",
    text: `<p>Pierwsi beta testerzy — pięć osób z sieci, designerzy których znam. Feedback po tygodniu: „to rozwiązuje problem który mam od roku". Jedna zdanie, ale warte więcej niż pięćdziesiąt komplementów. MVP trafia w punkt.</p>`,
    created_at: "2024-11-05T19:00:00.000Z",
    updated_at: "2024-11-05T19:00:00.000Z",
  },
  {
    id: "hist-093",
    date: "2024-11-11",
    mood_label: "Drained",
    mood_category: "Difficult",
    text: `<p>Tydzień po beta-launchu: praca w Kolibri, side projekt, terapia, treningi, życie towarzyskie — wszystko naraz i wszystko ważne. Czuję się jak pięć talerzy na raz. Muszę coś zdjąć ze stołu, tylko nie wiem co.</p>`,
    created_at: "2024-11-11T22:00:00.000Z",
    updated_at: "2024-11-11T22:00:00.000Z",
  },
  {
    id: "hist-094",
    date: "2024-11-17",
    mood_label: "Focused",
    mood_category: "Calm",
    text: `<p>Zdecydowałam: przez listopad side project dwa wieczory w tygodniu, nie codziennie. Reszta — odpoczynek, Kasia, książki. Sustainable pace zamiast sprintu do wypalenia. Chyba nauczyłam się czegoś przez ostatni rok i pół.</p>`,
    created_at: "2024-11-17T12:00:00.000Z",
    updated_at: "2024-11-17T12:00:00.000Z",
  },
  {
    id: "hist-095",
    date: "2024-11-23",
    mood_label: "Relaxed",
    mood_category: "Calm",
    text: `<p>Sobota bez planu — kawiarnia, rynek, stara księgarnia. Kupiłam trzy książki i spędziłam popołudnie na kanapie. Ani jednego Slacka. To właśnie jest zdrowie psychiczne: umieć wyjść z trybu roboczego bez poczucia winy.</p>`,
    created_at: "2024-11-23T17:30:00.000Z",
    updated_at: "2024-11-23T17:30:00.000Z",
  },
  {
    id: "hist-096",
    date: "2024-11-29",
    mood_label: "Content",
    mood_category: "Positive",
    text: `<p>Koniec listopada. Spoglądam wstecz: ten rok był inny niż się spodziewałam. Nie dramatyczny, nie przełomowy — stopniowy. Jakby wszystkie małe decyzje złożyły się w inną osobę. Dobry rodzaj zmiany.</p>`,
    created_at: "2024-11-29T21:00:00.000Z",
    updated_at: "2024-11-29T21:00:00.000Z",
  },

  // ─── GRUDZIEŃ 2024 ─────────────────────────────────────────────────────────
  {
    id: "hist-097",
    date: "2024-12-06",
    mood_label: "Excited",
    mood_category: "Positive",
    text: `<p>Poznałam Tomka — znajomy Kasi, pracuje w klimatycznym startupie, czyta te same książki co ja. Wyszliśmy na kawę, zostaliśmy na kolację, gadaliśmy pięć godzin. Nie pamiętam kiedy ostatnio czas tak mi zleciał przy nowej osobie.</p>`,
    created_at: "2024-12-06T23:30:00.000Z",
    updated_at: "2024-12-06T23:30:00.000Z",
  },
  {
    id: "hist-098",
    date: "2024-12-12",
    mood_label: "Joyful",
    mood_category: "Positive",
    text: `<p>Drugie spotkanie z Tomkiem — spacer po Plantach, potem ciepła herbata w jego ulubionym miejscu. Jest coś spokojnego w jego obecności — nie muszę być na pełnych obrotach. To świeże uczucie.</p>`,
    created_at: "2024-12-12T21:00:00.000Z",
    updated_at: "2024-12-12T21:00:00.000Z",
  },
  {
    id: "hist-099",
    date: "2024-12-19",
    mood_label: "Relaxed",
    mood_category: "Calm",
    text: `<p>Przedświąteczny tydzień. Zamknęłam wszystko w pracy przed urlopem — żaden mail, żaden Slack, zero. Jadę do rodziców ze spokojną głową. Pierwszy raz od lat naprawdę wyłączam się przed Świętami.</p>`,
    created_at: "2024-12-19T17:00:00.000Z",
    updated_at: "2024-12-19T17:00:00.000Z",
  },
  {
    id: "hist-100",
    date: "2024-12-26",
    mood_label: "Content",
    mood_category: "Positive",
    text: `<p>Góry między Świętami. Tomek dołączył do mnie i rodziców na dwa dni — trochę ryzykowne jak na trzecie spotkanie, ale wyszło lepiej niż dobrze. Tata go polubił, co jest dla mnie pewnymbarometrem. Śnieg, ciepłe ponczo, wieczorne rozmowy. Nie chcę żeby to się skończyło.</p>`,
    created_at: "2024-12-26T22:00:00.000Z",
    updated_at: "2024-12-26T22:00:00.000Z",
  },
  {
    id: "hist-101",
    date: "2024-12-31",
    mood_label: "Reflective",
    mood_category: "Calm",
    text: `<p>Koniec 2024. Dwa lata temu byłam na L4, rozklejona, bez kierunku. Teraz: dobra praca, żyjący side project, nowa relacja, terapia która działa. Nie wszystko jest idealne i część rzeczy nadal mnie straszy — ale jestem zdecydowanie dalej niż byłam. Dobry rok.</p>`,
    created_at: "2024-12-31T23:30:00.000Z",
    updated_at: "2024-12-31T23:30:00.000Z",
  },

  // ─── STYCZEŃ 2025 ──────────────────────────────────────────────────────────
  {
    id: "hist-102",
    date: "2025-01-06",
    mood_label: "Focused",
    mood_category: "Calm",
    text: `<p>Nowy rok, konkretny plan: Q1 — side project gotowy do publicznego launchu. Mam listę rzeczy do zrobienia, timeline, priorytety. Łukasz też wrócił z urlopu zmotywowany. Startujemy.</p>`,
    created_at: "2025-01-06T10:00:00.000Z",
    updated_at: "2025-01-06T10:00:00.000Z",
  },
  {
    id: "hist-103",
    date: "2025-01-11",
    mood_label: "Tired",
    mood_category: "Neutral",
    text: `<p>Styczeń ma tę właściwość że jest długi i ciemny i zimny. Wstałam dziś ciężko, praca ciężko, wieczór ciężko. Nic złego się nie dzieje — po prostu luty przed lutym. Znam to już i wiem że mija.</p>`,
    created_at: "2025-01-11T21:00:00.000Z",
    updated_at: "2025-01-11T21:00:00.000Z",
  },
  {
    id: "hist-104",
    date: "2025-01-16",
    mood_label: "Excited",
    mood_category: "Positive",
    text: `<p>Dałam projektowi nazwę: ResearchPal. Brzmi prosto i dokładnie opisuje co robi — AI-assisted narzędzie dla UX researcherów i designerów. Łukasz zarejestrował domenę. To taki moment kiedy coś staje się bardziej realne.</p>`,
    created_at: "2025-01-16T20:00:00.000Z",
    updated_at: "2025-01-16T20:00:00.000Z",
  },
  {
    id: "hist-105",
    date: "2025-01-22",
    mood_label: "Focused",
    mood_category: "Calm",
    text: `<p>Napisałam landing page — pierwsza strona publiczna ResearchPal. Trzy razy przepisałam nagłówek zanim poczułam że to brzmi jak ja, nie jak korporacyjny slogan. Copywriting jest trudniejszy niż UI. Podziwiam dobrych copywriterów.</p>`,
    created_at: "2025-01-22T16:30:00.000Z",
    updated_at: "2025-01-22T16:30:00.000Z",
  },
  {
    id: "hist-106",
    date: "2025-01-28",
    mood_label: "Anxious",
    mood_category: "Difficult",
    text: `<p>Wysłałam formularz early access do mojej sieci — 40 osób. Czekam na reakcje z uczuciem jakby wystawić się publicznie po raz pierwszy. Wiem logicznie że to tylko formularz, ale ciało reaguje jak przed publicznym wystąpieniem.</p>`,
    created_at: "2025-01-28T19:30:00.000Z",
    updated_at: "2025-01-28T19:30:00.000Z",
  },

  // ─── LUTY 2025 ─────────────────────────────────────────────────────────────
  {
    id: "hist-107",
    date: "2025-02-04",
    mood_label: "Joyful",
    mood_category: "Positive",
    text: `<p>28 zgłoszeń na early access w pierwszym tygodniu. Nie wiedziałam czego się spodziewać — może dziesięciu, może pięciu. Dwadzieścia osiem to sygnał że problem jest realny i że ludzie go czują. Tomek otworzył butelkę prosecco wieczorem i świętowaliśmy razem.</p>`,
    created_at: "2025-02-04T21:30:00.000Z",
    updated_at: "2025-02-04T21:30:00.000Z",
  },
  {
    id: "hist-108",
    date: "2025-02-10",
    mood_label: "Drained",
    mood_category: "Difficult",
    text: `<p>Cztery równoległe tory: Kolibri (nowy duży feature), ResearchPal (beta fixes), relacja z Tomkiem, terapia. Każdy z nich wymaga obecności i uwagi. Czuję że jestem w 25% przy każdym zamiast 100% przy jednym. Nie wiem jak to zrównoważyć.</p>`,
    created_at: "2025-02-10T20:00:00.000Z",
    updated_at: "2025-02-10T20:00:00.000Z",
  },
  {
    id: "hist-109",
    date: "2025-02-17",
    mood_label: "Reflective",
    mood_category: "Calm",
    text: `<p>Tydzień po wypaleniu — wzięłam dwa dni urlopu i celowo nic nie robiłam. Wróciłam z jedną myślą: nie można robić wszystkiego naraz i oczekiwać że wszystko będzie na poziomie. Coś musi ustąpić. Rozmowa z terapeutką za dwa dni.</p>`,
    created_at: "2025-02-17T18:00:00.000Z",
    updated_at: "2025-02-17T18:00:00.000Z",
  },
  {
    id: "hist-110",
    date: "2025-02-22",
    mood_label: "Content",
    mood_category: "Positive",
    text: `<p>Rozmowa z szefem: poprosiłam o 20% czasu na side projekt oficjalnie wpisany w mój work plan jako „AI research & tooling". Zdziwiło mnie że się zgodził bez wahania — powiedział że takie eksperymenty mają wartość dla całego teamu. Ulga i ekscytacja jednocześnie.</p>`,
    created_at: "2025-02-22T15:00:00.000Z",
    updated_at: "2025-02-22T15:00:00.000Z",
  },
  {
    id: "hist-111",
    date: "2025-02-27",
    mood_label: "Focused",
    mood_category: "Calm",
    text: `<p>Pierwszy piątek officjalnie zaalokowany na ResearchPal. Ośmiogodzinna sesja projektowa — żadnych spotkań, żadnych powiadomień. Skończyłam z nowym flow analizy wywiadów, który jest prostszy i szybszy od poprzedniego. Tak powinien wyglądać twórczy dzień.</p>`,
    created_at: "2025-02-27T18:30:00.000Z",
    updated_at: "2025-02-27T18:30:00.000Z",
  },

  // ─── MARZEC 2025 ───────────────────────────────────────────────────────────
  {
    id: "hist-112",
    date: "2025-03-05",
    mood_label: "Overwhelmed",
    mood_category: "Intense",
    text: `<p>Seria błędów w ResearchPal — coś popsuło się po aktualizacji API od dostawcy AI. Użytkownicy beta piszą, Łukasz debuguje, ja przepisuję kopię komunikatów błędów. To moje pierwsze prawdziwe „pożar produkcyjny" i czuję się jak amator. Przeżyjemy.</p>`,
    created_at: "2025-03-05T22:30:00.000Z",
    updated_at: "2025-03-05T22:30:00.000Z",
  },
  {
    id: "hist-113",
    date: "2025-03-09",
    mood_label: "Relaxed",
    mood_category: "Calm",
    text: `<p>Kryzys zażegnany. Łukasz naprawił, ja napisałam maila do betatestersów z wyjaśnieniem i przeprosinami. Połowa odpowiedziała że to rozumieją i że narzędzie im się podoba pomimo bugów. To daje dużo siły.</p>`,
    created_at: "2025-03-09T17:00:00.000Z",
    updated_at: "2025-03-09T17:00:00.000Z",
  },
  {
    id: "hist-114",
    date: "2025-03-14",
    mood_label: "Excited",
    mood_category: "Positive",
    text: `<p>Zaproponowałam prezentację ResearchPal na lokalnym meetupie UX — przyjęto. Za sześć tygodni będę stać przed ~80 designerami i opowiadać o tym co zbudowałam. Ekscytacja i panika w równych proporcjach. To dobry znak.</p>`,
    created_at: "2025-03-14T11:00:00.000Z",
    updated_at: "2025-03-14T11:00:00.000Z",
  },
  {
    id: "hist-115",
    date: "2025-03-20",
    mood_label: "Indifferent",
    mood_category: "Neutral",
    text: `<p>Środkowy marzec. Robię swoje, wszystko idzie do przodu ale bez dramatów. Czasem tak jest i to w porządku.</p>`,
    created_at: "2025-03-20T20:00:00.000Z",
    updated_at: "2025-03-20T20:00:00.000Z",
  },
  {
    id: "hist-116",
    date: "2025-03-26",
    mood_label: "Frustrated",
    mood_category: "Intense",
    text: `<p>Ktoś na LinkedIn skopiował dokładnie naszą koncepcję ResearchPal — nie dosłownie, ale widać skąd brał inspirację. Mam ochotę napisać coś sarkastycznego publicznie, ale nie napiszę. Zamiast tego skupiam się na tym żeby być szybsza niż oni.</p>`,
    created_at: "2025-03-26T19:00:00.000Z",
    updated_at: "2025-03-26T19:00:00.000Z",
  },

  // ─── KWIECIEŃ 2025 ─────────────────────────────────────────────────────────
  {
    id: "hist-117",
    date: "2025-04-03",
    mood_label: "Focused",
    mood_category: "Calm",
    text: `<p>Dwa tygodnie do meetupu. Ćwiczę prezentację — stojąc, z timerem, przed lustrem. Treść jest dobra, ale tempo za szybkie kiedy nerwowo. Dlatego ćwiczę. Tomek słucha cierpliwie po raz szósty i daje konstruktywny feedback.</p>`,
    created_at: "2025-04-03T20:30:00.000Z",
    updated_at: "2025-04-03T20:30:00.000Z",
  },
  {
    id: "hist-118",
    date: "2025-04-10",
    mood_label: "Anxious",
    mood_category: "Difficult",
    text: `<p>Tydzień przed prezentacją — najgorszy możliwy czas na imposter syndrome. „Kto ja jestem żeby uczyć innych o AI?" Wiem że to bzdura, wiem że wiem wystarczająco dużo, wiem że ludzie przyszli posłuchać. A jednak.</p>`,
    created_at: "2025-04-10T21:00:00.000Z",
    updated_at: "2025-04-10T21:00:00.000Z",
  },
  {
    id: "hist-119",
    date: "2025-04-17",
    mood_label: "Joyful",
    mood_category: "Positive",
    text: `<p>Meetup za mną. Sala była pełna, ludzie słuchali, pytania były dobre i szczere. Po prezentacji kolejka do rozmowy — pięć osób poprosiło o dostęp do ResearchPal. To jest ten moment, dla którego warto było się bać. Tomek czekał z kwiatami pod wyjściem.</p>`,
    created_at: "2025-04-17T22:00:00.000Z",
    updated_at: "2025-04-17T22:00:00.000Z",
  },
  {
    id: "hist-120",
    date: "2025-04-23",
    mood_label: "Relaxed",
    mood_category: "Calm",
    text: `<p>Długi weekend — wyjazdik z Tomkiem do Krakowa. Żadnych planów, tylko chodzenie i jedzenie i rozmowy. Powiedział że jest ze mnie dumny i że widzi jak zmieniałam się przez ostatni rok. Poczułam się widziana. To rzadkie uczucie.</p>`,
    created_at: "2025-04-23T19:30:00.000Z",
    updated_at: "2025-04-23T19:30:00.000Z",
  },
  {
    id: "hist-121",
    date: "2025-04-29",
    mood_label: "Focused",
    mood_category: "Calm",
    text: `<p>Po meetupie wzrosło zainteresowanie — lista czekających na dostęp urosła do 120 osób. Razem z Łukaszem ustaliliśmy datę publicznego launchu: 15 czerwca. Realnie, z buforem. To ważne żeby nie obiecywać za dużo.</p>`,
    created_at: "2025-04-29T16:00:00.000Z",
    updated_at: "2025-04-29T16:00:00.000Z",
  },

  // ─── MAJ 2025 ──────────────────────────────────────────────────────────────
  {
    id: "hist-122",
    date: "2025-05-07",
    mood_label: "Tired",
    mood_category: "Neutral",
    text: `<p>Pre-launch grind. Każdy wieczór to coś do poprawki, każdy poranek to nowy feedback od beta. Zmęczona, ale to inne zmęczenie niż to z agencji — tamto było z bezsensu, to jest ze znaczenia. Nie mylić.</p>`,
    created_at: "2025-05-07T22:00:00.000Z",
    updated_at: "2025-05-07T22:00:00.000Z",
  },
  {
    id: "hist-123",
    date: "2025-05-13",
    mood_label: "Content",
    mood_category: "Positive",
    text: `<p>ResearchPal ma teraz płatny plan. Pierwsze trzy osoby zapłaciły. Dziesięć dolarów miesięcznie każda — łącznie 30 USD. Mało, ale to realny pieniądz za coś co zbudowałam od zera. Łukasz powiedział: „teraz to już startup". Może ma rację.</p>`,
    created_at: "2025-05-13T18:30:00.000Z",
    updated_at: "2025-05-13T18:30:00.000Z",
  },
  {
    id: "hist-124",
    date: "2025-05-19",
    mood_label: "Reflective",
    mood_category: "Calm",
    text: `<p>Dwa lata od pierwszego wpisu w tym dzienniku. Wtedy pisałam z kanapy na L4, przestraszona i zmęczona. Teraz piszę ze stołu w nowym miejscu — projektuję własny produkt, mam partnera, terapeuta mówi że radzę sobie wyjątkowo dobrze. Mam wrażenie że to jakaś inna osoba. Ale to wciąż ja.</p>`,
    created_at: "2025-05-19T21:00:00.000Z",
    updated_at: "2025-05-19T21:00:00.000Z",
  },
  {
    id: "hist-125",
    date: "2025-05-25",
    mood_label: "Drained",
    mood_category: "Difficult",
    text: `<p>Trzy tygodnie przed launchem i czuję się jak sprężyna nakręcona za mocno. Tomek powiedział że ostatnio jestem „nieobecna nawet kiedy jestem". Ma rację. Muszę znaleźć sposób żeby przez te trzy tygodnie nie stracić tego co ważne poza pracą.</p>`,
    created_at: "2025-05-25T20:00:00.000Z",
    updated_at: "2025-05-25T20:00:00.000Z",
  },

  // ─── CZERWIEC 2025 ─────────────────────────────────────────────────────────
  {
    id: "hist-126",
    date: "2025-06-03",
    mood_label: "Anxious",
    mood_category: "Difficult",
    text: `<p>Dwa tygodnie. Lista do zrobienia wciąż zbyt długa, priorytetyzuję bezlitośnie — co musi być na launch, co może poczekać. Ciężkie decyzje, bo każda rzecz której nie zrobimy to coś co ktoś odkryje i powie „ale słabe". Uczę się że done jest lepsze niż perfect.</p>`,
    created_at: "2025-06-03T22:00:00.000Z",
    updated_at: "2025-06-03T22:00:00.000Z",
  },
  {
    id: "hist-127",
    date: "2025-06-10",
    mood_label: "Focused",
    mood_category: "Calm",
    text: `<p>Tydzień przed launchem — wszystkie kluczowe rzeczy gotowe, testuję po raz dziesiąty, piszę post na Product Hunt. Jestem spokojna, co mnie trochę niepokoi — to nie jest mój zwykły stan przed czymś ważnym. Może naprawdę dojrzewam?</p>`,
    created_at: "2025-06-10T16:00:00.000Z",
    updated_at: "2025-06-10T16:00:00.000Z",
  },
  {
    id: "hist-128",
    date: "2025-06-15",
    mood_label: "Excited",
    mood_category: "Positive",
    text: `<p>DZIEŃ LAUNCHU. ResearchPal jest publicznie dostępny. Post na Product Hunt, newsletter do listy 180 osób, posty na LinkedInie i Twitterze. Siedzę i patrzę jak przychodzą rejestracje. Pięćdziesiąt w pierwszej godzinie. Łukasz piszę caps-lockiem przez Slacka. To się dzieje.</p>`,
    created_at: "2025-06-15T11:30:00.000Z",
    updated_at: "2025-06-15T11:30:00.000Z",
  },
  {
    id: "hist-129",
    date: "2025-06-18",
    mood_label: "Overwhelmed",
    mood_category: "Intense",
    text: `<p>Trzy dni po launchu: 340 rejestracji, kilkadziesiąt maili z pytaniami, dwa błędy które trzeba naprawić na gorąco, jeden bardzo krytyczny post w komentarzach Product Hunt. Wszystkiego naraz za dużo. Jutro segreguję priorytety, dziś jestem po prostu zmęczona sukcesem.</p>`,
    created_at: "2025-06-18T22:30.000Z",
    updated_at: "2025-06-18T22:30:00.000Z",
  },
  {
    id: "hist-130",
    date: "2025-06-24",
    mood_label: "Content",
    mood_category: "Positive",
    text: `<p>Tydzień po launchu, kurz opada. 410 zarejestrowanych, 28 płatnych subskrybentów, jeden artykuł w branżowym newsletterze który nas opisał. To nie jest unicorn-exit, to jest solidny, uczciwy start. Jestem z tego dumna bardziej niż z czegokolwiek wcześniej w karierze.</p>`,
    created_at: "2025-06-24T18:00:00.000Z",
    updated_at: "2025-06-24T18:00:00.000Z",
  },

  // ─── LIPIEC 2025 ───────────────────────────────────────────────────────────
  // [lipiec 1-13 — zasłużony urlop, brak wpisów]
  {
    id: "hist-131",
    date: "2025-07-14",
    mood_label: "Relaxed",
    mood_category: "Calm",
    text: `<p>Dwa tygodnie na Majorce z Tomkiem. Pierwsze dwa dni byłam niezdolna do prawdziwego odpoczynku — ciągle sprawdzałam maile w myślach. Potem coś puściło. Ostatnie pięć dni to czysty odpoczynek, zero branży, dużo wody i słońca.</p>`,
    created_at: "2025-07-14T19:00:00.000Z",
    updated_at: "2025-07-14T19:00:00.000Z",
  },
  {
    id: "hist-132",
    date: "2025-07-22",
    mood_label: "Focused",
    mood_category: "Calm",
    text: `<p>Wróciłam z urlopu i zamiast rzucać się na zaległy backlog, spędziłam pierwszy dzień na analizie danych z pierwszego miesiąca. Które funkcje są używane, gdzie są odpływy, co piszą w feedbacku. To mój nowy priorytet: rozumieć użytkowników zanim zacznę cokolwiek budować.</p>`,
    created_at: "2025-07-22T15:00.000Z",
    updated_at: "2025-07-22T15:00:00.000Z",
  },
  {
    id: "hist-133",
    date: "2025-07-29",
    mood_label: "Reflective",
    mood_category: "Calm",
    text: `<p>Piję kawę na balkonie rano — nowy rytuał odkąd pracuję hybrydowo. Myślę o tym jak bardzo zmieniła się moja relacja z AI przez ostatnie dwa lata. Zaczęło się od strachu, szło przez fascynację, przez naukę, teraz to po prostu część jak pracuję. Naturalne i zintegrowane.</p>`,
    created_at: "2025-07-29T08:30.000Z",
    updated_at: "2025-07-29T08:30:00.000Z",
  },

  // ─── SIERPIEŃ 2025 ─────────────────────────────────────────────────────────
  {
    id: "hist-134",
    date: "2025-08-05",
    mood_label: "Drained",
    mood_category: "Difficult",
    text: `<p>Post-launch fatigue jest realny. Myślałam że launch to koniec sprint, ale to był tylko koniec jednego etapu — teraz zaczyna się nowy, cięższy: wzrost, retencja, monetyzacja. Trochę mnie to przytłacza, bo nie mam roadmapy jak to robić. Szukam mentora.</p>`,
    created_at: "2025-08-05T20:00.000Z",
    updated_at: "2025-08-05T20:00:00.000Z",
  },
  {
    id: "hist-135",
    date: "2025-08-11",
    mood_label: "Content",
    mood_category: "Positive",
    text: `<p>Odezwała się Ania — założycielka małego SaaS dla designerów, chce pogadać o naszych doświadczeniach. Wspaniałe uczucie kiedy ktoś na podobnej ścieżce szuka połączenia. Umówiłyśmy się na kawę. Może z tego wyjdzie coś więcej niż rozmowa.</p>`,
    created_at: "2025-08-11T14:00.000Z",
    updated_at: "2025-08-11T14:00:00.000Z",
  },
  {
    id: "hist-136",
    date: "2025-08-17",
    mood_label: "Focused",
    mood_category: "Calm",
    text: `<p>Kawa z Anią — trzy godziny o budowaniu produktów, znajdowaniu klientów, balansie. Wspólne odkrycie: obydwie zmagamy się z tym samym — że design to coś co lubimy, ale prowadzenie biznesu to zestaw umiejętności, których nikt nas nie uczył. Mam swojego pierwszego mentora.</p>`,
    created_at: "2025-08-17T17:30.000Z",
    updated_at: "2025-08-17T17:30:00.000Z",
  },
  {
    id: "hist-137",
    date: "2025-08-23",
    mood_label: "Tired",
    mood_category: "Neutral",
    text: `<p>Sierpień jest jak czerwiec — ciepło, leniwie, ale bez prawdziwego oddechu bo wiem że wrzesień przyjdzie z pełnym obciążeniem. Staram się korzystać z tych ostatnich dni lata. Dzisiaj popoludniu zamknęłam laptopa i poszłam nad rzekę.</p>`,
    created_at: "2025-08-23T20:00.000Z",
    updated_at: "2025-08-23T20:00:00.000Z",
  },
  {
    id: "hist-138",
    date: "2025-08-29",
    mood_label: "Excited",
    mood_category: "Positive",
    text: `<p>ResearchPal osiągnął 60 płatnych subskrybentów — 600 USD MRR. Nie jest to jeszcze wolność finansowa, ale to dowód że model działa. Ania mówi że to dobry moment na pierwszą podwyżkę cen dla nowych użytkowników. Przemyślę to przez weekend.</p>`,
    created_at: "2025-08-29T16:30.000Z",
    updated_at: "2025-08-29T16:30:00.000Z",
  },

  // ─── WRZESIEŃ 2025 ─────────────────────────────────────────────────────────
  {
    id: "hist-139",
    date: "2025-09-04",
    mood_label: "Focused",
    mood_category: "Calm",
    text: `<p>Wrzesień — powrót pełnego biegu. Kolibri ruszyło z dużym projektem na Q4, ResearchPal wymaga uwagi, Tomek planuje jakiś wspólny wyjazd na jesień. Wszystko jest ważne i nic nie jest pilne. To dobry stan.</p>`,
    created_at: "2025-09-04T10:00:00.000Z",
    updated_at: "2025-09-04T10:00:00.000Z",
  },
  {
    id: "hist-140",
    date: "2025-09-10",
    mood_label: "Reflective",
    mood_category: "Calm",
    text: `<p>Rozmowa z terapeutką o tym co się zmieniło przez dwa lata terapii. Lista jest długa: granice, mówienie nie, rozróżnianie lęku od intuicji, zaufanie do siebie w zawodowych decyzjach. Powiedziała że mam już narzędzia i pytanie jest kiedy chcę zakończyć regularne spotkania. Jeszcze nie teraz, ale wkrótce.</p>`,
    created_at: "2025-09-10T18:00:00.000Z",
    updated_at: "2025-09-10T18:00:00.000Z",
  },
  {
    id: "hist-141",
    date: "2025-09-16",
    mood_label: "Content",
    mood_category: "Positive",
    text: `<p>Podniosłam ceny ResearchPal o 30% dla nowych użytkowników zgodnie z radą Ani. Wzięło mnie to tydzień żeby się przemóc psychicznie — klasyczny strach before pricing. Po zmianie: wskaźnik rejestracji prawie bez zmian. Ania miała rację.</p>`,
    created_at: "2025-09-16T15:00:00.000Z",
    updated_at: "2025-09-16T15:00:00.000Z",
  },
  {
    id: "hist-142",
    date: "2025-09-22",
    mood_label: "Tired",
    mood_category: "Neutral",
    text: `<p>Koniec tygodnia i jestem zwyczajnie zmęczona. Dobra zmęczona — nie z desperacji, tylko z tempa. Jutro sobota, plan: długi spacer, herbata, nic więcej.</p>`,
    created_at: "2025-09-22T21:00:00.000Z",
    updated_at: "2025-09-22T21:00:00.000Z",
  },
  {
    id: "hist-143",
    date: "2025-09-28",
    mood_label: "Joyful",
    mood_category: "Positive",
    text: `<p>Wyjazd z Tomkiem do Berlina — długi weekend, muzea, kawiarnie, targ w Mauerpark. Niemcy są piękne jesienią. Tomek powiedział że myśli o wspólnym mieszkaniu — nie jako pytanie, ale jako pomysł do omówienia. Powiedziałam że chcę o tym porozmawiać poważnie. To znaczy dużo.</p>`,
    created_at: "2025-09-28T22:00.000Z",
    updated_at: "2025-09-28T22:00:00.000Z",
  },

  // ─── PAŹDZIERNIK 2025 ──────────────────────────────────────────────────────
  {
    id: "hist-144",
    date: "2025-10-06",
    mood_label: "Anxious",
    mood_category: "Difficult",
    text: `<p>Rozmowa z Tomkiem o wspólnym mieszkaniu. Cieszę się i boję się jednocześnie — wspólne mieszkanie to zupełnie inna liga niż weekendowe wyjazdy. Wiem że to irracjonalne, wiem że go kocham, wiem że chcę tego. I mimo to — lęk. Terapeutka mówi że to normalne.</p>`,
    created_at: "2025-10-06T20:00.000Z",
    updated_at: "2025-10-06T20:00:00.000Z",
  },
  {
    id: "hist-145",
    date: "2025-10-12",
    mood_label: "Excited",
    mood_category: "Positive",
    text: `<p>Zaczęłyśmy z Tomkiem oglądać mieszkania. Pierwsze trzy były albo za małe albo za drogie albo za ciemne. Ale sam fakt że razem przeglądamy oferty i rozmawiamy o tym co ważne — to już jest inne życie. Dobre uczucie.</p>`,
    created_at: "2025-10-12T18:30.000Z",
    updated_at: "2025-10-12T18:30:00.000Z",
  },
  {
    id: "hist-146",
    date: "2025-10-18",
    mood_label: "Focused",
    mood_category: "Calm",
    text: `<p>Poważna rozmowa w Kolibri: szef zaproponował mi rolę design lead — prowadzenie małego zespołu, więcej strategii, mniej własnych makiet. Potrzebuję tygodnia żeby przemyśleć. To jest dokładnie ten rodzaj decyzji, który rok temu zrobiłabym pod presją a nie z głowy.</p>`,
    created_at: "2025-10-18T16:00.000Z",
    updated_at: "2025-10-18T16:00:00.000Z",
  },
  {
    id: "hist-147",
    date: "2025-10-24",
    mood_label: "Reflective",
    mood_category: "Calm",
    text: `<p>Przemyślałam propozycję design leada. Decyzja: tak, ale z warunkami — zachowuję 20% czasu na ResearchPal, mamy jasne oczekiwania od pierwszego dnia. Szef się zgodził. Jestem zaskoczona jak naturalnie to mi poszło — negocjowanie zamiast przyjmowania wszystkiego.</p>`,
    created_at: "2025-10-24T14:00.000Z",
    updated_at: "2025-10-24T14:00:00.000Z",
  },
  {
    id: "hist-148",
    date: "2025-10-30",
    mood_label: "Content",
    mood_category: "Positive",
    text: `<p>Halloween — Tomek wymyślił przebrania ostatniej chwili (para kluczy i zamek, trochę absurdalne) i byliśmy na imprezie u jego znajomych. Śmiałam się szczerze pierwszy raz od dawna nie z powodu czegoś ważnego, tylko dlatego że było po prostu wesoło. To też jest ważne.</p>`,
    created_at: "2025-10-30T23:00.000Z",
    updated_at: "2025-10-30T23:00:00.000Z",
  },

  // ─── LISTOPAD 2025 ─────────────────────────────────────────────────────────
  {
    id: "hist-149",
    date: "2025-11-06",
    mood_label: "Overwhelmed",
    mood_category: "Intense",
    text: `<p>Pierwszy tydzień jako design lead — okazuje się że rola to zupełnie inny zestaw problemów. Mniej robię, więcej blokuję, więcej priorytetuję dla innych. Czuję się jak kontroler ruchu lotniczego który nigdy nie latał. Dostosowuję się.</p>`,
    created_at: "2025-11-06T22:00.000Z",
    updated_at: "2025-11-06T22:00:00.000Z",
  },
  {
    id: "hist-150",
    date: "2025-11-13",
    mood_label: "Focused",
    mood_category: "Calm",
    text: `<p>Drugi tydzień jako lead — już trochę lepiej. Nauczyłam się że mój job jako lead to usuwać przeszkody, nie je tworzyć. Zrobiłam 1:1 z każdą osobą w teamie. Wszystko czego się dowiedziałam w 4 rozmowach było ważniejsze niż miesiąc statu meetings.</p>`,
    created_at: "2025-11-13T17:00.000Z",
    updated_at: "2025-11-13T17:00:00.000Z",
  },
  {
    id: "hist-151",
    date: "2025-11-20",
    mood_label: "Sad",
    mood_category: "Difficult",
    text: `<p>Mała designerka z mojego teamu — Zuza, rok po studiach — powiedziała że boi się AI. Usłyszałam siebie z 2023 roku. Porozmawiałam z nią przez godzinę o tym jak ja przez to przechodziłam. Trochę mnie to rozbroiło emocjonalnie, bo przypomniało jak bardzo byłam wtedy zagubiona.</p>`,
    created_at: "2025-11-20T19:00.000Z",
    updated_at: "2025-11-20T19:00:00.000Z",
  },
  {
    id: "hist-152",
    date: "2025-11-27",
    mood_label: "Relaxed",
    mood_category: "Calm",
    text: `<p>Znaleźliśmy mieszkanie — duże, jasne, blisko parku, w granicach budżetu. Tomek powiedział „to jest nasze" jeszcze podczas oglądania. Podpisujemy umowę za tydzień. Przeprowadzka w grudniu. Życie się zmienia konkretnie i nieodwracalnie — i to jest dokładnie dobra zmiana.</p>`,
    created_at: "2025-11-27T21:00.000Z",
    updated_at: "2025-11-27T21:00:00.000Z",
  },

  // ─── GRUDZIEŃ 2025 ─────────────────────────────────────────────────────────
  {
    id: "hist-153",
    date: "2025-12-06",
    mood_label: "Tired",
    mood_category: "Neutral",
    text: `<p>Przeprowadzka. Pudła, chaos, IKEA, pizza na podłodze między stosami rzeczy. Jestem wykończona fizycznie ale jest w tym też coś wyzwalającego — stare rzeczy oddaję, nowe miejsce, nowy etap. Tomek jest dobry w przeprowadzkach — nie traci spokoju kiedy ja tracę.</p>`,
    created_at: "2025-12-06T22:30.000Z",
    updated_at: "2025-12-06T22:30:00.000Z",
  },
  {
    id: "hist-154",
    date: "2025-12-13",
    mood_label: "Content",
    mood_category: "Positive",
    text: `<p>Pierwsze dwa tygodnie we wspólnym mieszkaniu. Najtrudniejsza rzecz: dogadanie się co do temperatur w nocy. Najlepsza: poranna kawa razem przed pracą. Balans wychodzi na plus.</p>`,
    created_at: "2025-12-13T09:30.000Z",
    updated_at: "2025-12-13T09:30:00.000Z",
  },
  {
    id: "hist-155",
    date: "2025-12-22",
    mood_label: "Joyful",
    mood_category: "Positive",
    text: `<p>Pierwsze Święta razem z Tomkiem — jego rodzina, moja rodzina, jedno spotkanie łączone w nowym mieszkaniu. Trochę chaotyczne, dużo jedzenia, dużo głośnego śmiechu. To jest dom.</p>`,
    created_at: "2025-12-22T20:00.000Z",
    updated_at: "2025-12-22T20:00:00.000Z",
  },
  {
    id: "hist-156",
    date: "2025-12-31",
    mood_label: "Reflective",
    mood_category: "Calm",
    text: `<p>Ostatni dzień 2025. Siedzimy z Tomkiem przy winie, za oknem miasto świętuje. Myślę o tym jak ten rok był pełny — launch produktu, nowa rola, nowe mieszkanie, nowy rozdział. Jestem zmęczona i wdzięczna jednocześnie. To dobry sposób kończyć rok.</p>`,
    created_at: "2025-12-31T23:00.000Z",
    updated_at: "2025-12-31T23:00:00.000Z",
  },

  // ─── STYCZEŃ 2026 ──────────────────────────────────────────────────────────
  {
    id: "hist-157",
    date: "2026-01-07",
    mood_label: "Focused",
    mood_category: "Calm",
    text: `<p>Nowy rok ze świeżą głową. ResearchPal: 95 płatnych subskrybentów, prawie 1000 USD MRR. Cel na 2026: dojść do 200 płatnych i 2k MRR do końca roku. Ambitne ale realne. Mam plan.</p>`,
    created_at: "2026-01-07T10:00.000Z",
    updated_at: "2026-01-07T10:00:00.000Z",
  },
  {
    id: "hist-158",
    date: "2026-01-13",
    mood_label: "Relaxed",
    mood_category: "Calm",
    text: `<p>Długi wieczór z Kasią — nie widziałyśmy się od Świąt. Opowiedziałam jej o wszystkim co się zmieniło: mieszkanie, rola, ResearchPal. Ona też zmienia pracę — idzie do agencji specjalizującej się w AI design. Obydwie byłyśmy tutaj dwa lata temu przestraszone. Teraz jesteśmy tutaj.</p>`,
    created_at: "2026-01-13T22:30.000Z",
    updated_at: "2026-01-13T22:30:00.000Z",
  },
  {
    id: "hist-159",
    date: "2026-01-20",
    mood_label: "Anxious",
    mood_category: "Difficult",
    text: `<p>Nowe modele AI wychodzą co miesiąc i każdy jest lepszy od poprzedniego. Zuza z mojego teamu znowu jest przestraszona. Ja tym razem nie jestem — ale rozumiem jej lęk i wiem że to nie jest irracjonalne. Zmiana jest szybka i niepewność jest normalna. Staramy się o tym rozmawiać jako team.</p>`,
    created_at: "2026-01-20T19:00.000Z",
    updated_at: "2026-01-20T19:00:00.000Z",
  },
  {
    id: "hist-160",
    date: "2026-01-26",
    mood_label: "Content",
    mood_category: "Positive",
    text: `<p>Zorganizowałam w Kolibri warsztat: „AI dla designerów — od strachu do narzędzia". Przyszło 12 osób, w tym kilka z lękiem podobnym do mojego sprzed lat. Spędziłam dwa godziny na tym żeby opowiedzieć swoją drogę i pokazać konkretne przykłady. Dostałam więcej podziękowań niż po jakimkolwiek projekcie produktowym.</p>`,
    created_at: "2026-01-26T18:00.000Z",
    updated_at: "2026-01-26T18:00:00.000Z",
  },

  // ─── LUTY 2026 ─────────────────────────────────────────────────────────────
  {
    id: "hist-161",
    date: "2026-02-05",
    mood_label: "Tired",
    mood_category: "Neutral",
    text: `<p>Luty jest moim najtrudniejszym miesiącem — ciemno, zimno, jeszcze daleko do wiosny. Ale wiem już że to mija i że depresja sezonowa to nie słabość, to fizjologia. Biorę witaminę D, chodzę na siłownię, staram się wychodzić na zewnątrz codziennie. To pomaga.</p>`,
    created_at: "2026-02-05T20:00.000Z",
    updated_at: "2026-02-05T20:00:00.000Z",
  },
  {
    id: "hist-162",
    date: "2026-02-12",
    mood_label: "Focused",
    mood_category: "Calm",
    text: `<p>Nowa funkcja w ResearchPal: automatyczna analiza sentymentu w odpowiedziach użytkowników. Dwa miesiące pracy Łukasza, tydzień moich testów UX. Wyniki z beta: użytkownicy spędzają 40% mniej czasu na analizie. To konkretna wartość, nie tylko feature list.</p>`,
    created_at: "2026-02-12T15:00.000Z",
    updated_at: "2026-02-12T15:00:00.000Z",
  },
  {
    id: "hist-163",
    date: "2026-02-20",
    mood_label: "Reflective",
    mood_category: "Calm",
    text: `<p>Ostatnia sesja z terapeutką jako regularne spotkanie — zdecydowałam że jestem gotowa. Umówiłyśmy się że w razie potrzeby zawsze mogę wrócić. Wychodzę z poczuciem że dostałam narzędzia, których naprawdę nauczyłam się używać. Dwa i pół roku terapii to inwestycja która się zwróciła wielokrotnie.</p>`,
    created_at: "2026-02-20T17:30.000Z",
    updated_at: "2026-02-20T17:30:00.000Z",
  },
  {
    id: "hist-164",
    date: "2026-02-27",
    mood_label: "Bored",
    mood_category: "Neutral",
    text: `<p>Jeden z tych tygodni gdzie wszystko działa ale nic nie iskrzy. Robię swoje, jest dobrze, ale brakuje mi jakiegoś nowego wyzwania lub pomysłu. Może to sygnał że czas na coś nowego — nowy projekt, nowy kurs, nowe pytanie. Poszukam w weekend.</p>`,
    created_at: "2026-02-27T21:00.000Z",
    updated_at: "2026-02-27T21:00:00.000Z",
  },

  // ─── MARZEC 2026 ───────────────────────────────────────────────────────────
  {
    id: "hist-165",
    date: "2026-03-05",
    mood_label: "Excited",
    mood_category: "Positive",
    text: `<p>Znalazłam nowe wyzwanie — zgłosiłam ResearchPal do europejskiego programu akceleracyjnego dla design-tech startupów. Deadline za trzy tygodnie, wymaga porządnego deck i financial model. Łukasz mówi że nie mamy szans, ja mówię że nie wiemy dopóki nie spróbujemy.</p>`,
    created_at: "2026-03-05T11:00.000Z",
    updated_at: "2026-03-05T11:00:00.000Z",
  },
  {
    id: "hist-166",
    date: "2026-03-12",
    mood_label: "Focused",
    mood_category: "Calm",
    text: `<p>Tydzień na deck do akceleratora. Używam AI do pierwszych draftów, ale każde zdanie jest weryfikowane i przepisywane — bo inwestorzy czytają tysiące takich dokumentów i od razu czują kiedy coś nie jest autentyczne. Mój głos ma być w tym, nie ChatGPT.</p>`,
    created_at: "2026-03-12T16:00.000Z",
    updated_at: "2026-03-12T16:00:00.000Z",
  },
  {
    id: "hist-167",
    date: "2026-03-19",
    mood_label: "Drained",
    mood_category: "Difficult",
    text: `<p>Aplikacja wysłana. Osiem godzin dziennie przez dwa tygodnie — razem z regularną pracą to było za dużo. Tomek wzięł na siebie gotowanie i logistykę bez słowa skargi. Nie wiem jak on to robi. Jestem mu za to bardzo wdzięczna.</p>`,
    created_at: "2026-03-19T20:00.000Z",
    updated_at: "2026-03-19T20:00:00.000Z",
  },
  {
    id: "hist-168",
    date: "2026-03-27",
    mood_label: "Relaxed",
    mood_category: "Calm",
    text: `<p>Tydzień regeneracji po aplikacji. Tomek zaplanował weekend w górach — tylko my, cisza, długie spacery po śniegu. Potrzebowałam tego bardziej niż wiedziałam. Wróciłam z poczuciem że mam jeszcze rezerwy.</p>`,
    created_at: "2026-03-27T18:30.000Z",
    updated_at: "2026-03-27T18:30:00.000Z",
  },

  // ─── KWIECIEŃ 2026 ─────────────────────────────────────────────────────────
  {
    id: "hist-169",
    date: "2026-04-07",
    mood_label: "Joyful",
    mood_category: "Positive",
    text: `<p>ResearchPal dostał się do drugiego etapu akceleracji — rozmowa z jury za trzy tygodnie. Łukasz napisał dużymi literami przez Slacka. Ja siedziałam cicho przez chwilę, a potem zadzwoniłam do mamy. Ona zawsze jest pierwsza kiedy jest coś dobrego.</p>`,
    created_at: "2026-04-07T15:00.000Z",
    updated_at: "2026-04-07T15:00:00.000Z",
  },
  {
    id: "hist-170",
    date: "2026-04-14",
    mood_label: "Anxious",
    mood_category: "Difficult",
    text: `<p>Przygotowania do rozmowy z jury akceleracji. Ćwiczę odpowiedzi na trudne pytania — o competition, o retention, o exit. To zupełnie inny stres niż design presentation — tam oceniają estetykę i użyteczność, tu oceniają czy myślę jak founder. Nie wiem jeszcze czy jestem founderem.</p>`,
    created_at: "2026-04-14T21:00.000Z",
    updated_at: "2026-04-14T21:00:00.000Z",
  },
  {
    id: "hist-171",
    date: "2026-04-22",
    mood_label: "Reflective",
    mood_category: "Calm",
    text: `<p>Rozmowa z jury za mną. Była trudna, dobre pytania, kilka momentów gdzie nie znałam odpowiedzi i powiedziałam wprost że nie wiem. Wyniki za tydzień. Niezależnie od rezultatu: uczę się jak rozmawiać o produkcie z perspektywy biznesowej. To cenne samo w sobie.</p>`,
    created_at: "2026-04-22T18:00.000Z",
    updated_at: "2026-04-22T18:00:00.000Z",
  },
  {
    id: "hist-172",
    date: "2026-04-29",
    mood_label: "Sad",
    mood_category: "Difficult",
    text: `<p>Nie dostałyśmy się do akceleratora. Feedback: „obiecujący produkt, zbyt wczesna trakcja, za rok spróbujcie ponownie". Wiedziałam że to możliwe i mimo to boli. Tomek przyniósł mi ulubioną kawę i siedział obok bez mówienia czegokolwiek — dokładnie tego potrzebowałam. Jutro wracam do roboty.</p>`,
    created_at: "2026-04-29T19:00.000Z",
    updated_at: "2026-04-29T19:00:00.000Z",
  },

  // ─── MAJ 2026 ──────────────────────────────────────────────────────────────
  {
    id: "hist-173",
    date: "2026-05-06",
    mood_label: "Focused",
    mood_category: "Calm",
    text: `<p>Tydzień po odmowie z akceleratora — wróciłam mocniejsza. Wzięłam feedback serio: trakcja. Przez maj koncentruję się wyłącznie na wzroście bazy płatnych użytkowników. Mam trzy konkretne hipotezy do przetestowania. Działam jak designerka — badając zanim decyduję.</p>`,
    created_at: "2026-05-06T11:00.000Z",
    updated_at: "2026-05-06T11:00:00.000Z",
  },
  {
    id: "hist-174",
    date: "2026-05-13",
    mood_label: "Content",
    mood_category: "Positive",
    text: `<p>110 płatnych subskrybentów. Mały krok, ale konsekwentny wzrost. Ania mówi że consystency w SaaS jest ważniejsza od viral moments. Uczę się myśleć długoterminowo — coraz lepiej mi idzie.</p>`,
    created_at: "2026-05-13T17:00.000Z",
    updated_at: "2026-05-13T17:00:00.000Z",
  },
  {
    id: "hist-175",
    date: "2026-05-20",
    mood_label: "Relaxed",
    mood_category: "Calm",
    text: `<p>Wiosna jest w pełni. Siedzę z kawą przy otwartym oknie — słońce, ptaki, zapach bzu z parku. Tomek jeszcze śpi. Za dwie godziny zaplanowaliśmy śniadanie poza domem. W małych rzeczach jest więcej niż myślałam.</p>`,
    created_at: "2026-05-20T08:00.000Z",
    updated_at: "2026-05-20T08:00:00.000Z",
  },
  {
    id: "hist-176",
    date: "2026-05-27",
    mood_label: "Reflective",
    mood_category: "Calm",
    text: `<p>Trzy lata od początku tego dziennika. Wtedy byłam rozklejona na L4 i nie wiedziałam co z sobą zrobić. Teraz: design lead, side project z rosnącą trakcją, Tomek, nowe mieszkanie, koniec terapii jako regularnego wsparcia. Nie wszystko jest idealne — nigdy nie będzie. Ale wiem kim jestem i czego chcę. To jest coś.</p>`,
    created_at: "2026-05-27T21:00.000Z",
    updated_at: "2026-05-27T21:00:00.000Z",
  },

  // ─── CZERWIEC 2026 ─────────────────────────────────────────────────────────
  {
    id: "hist-177",
    date: "2026-06-03",
    mood_label: "Excited",
    mood_category: "Positive",
    text: `<p>Ania zaproponowała coś nieoczekiwanego: połączenie ResearchPal z jej produktem — ona ma bazę użytkowników, ja mam lepszą technologię AI. Wstępne rozmowy zaczęte. Nie wiem dokąd to zaprowadzi, ale jest w tym energia którą lubię — ta sama co przy pierwszym pomyśle na produkt.</p>`,
    created_at: "2026-06-03T19:30.000Z",
    updated_at: "2026-06-03T19:30:00.000Z",
  },
  {
    id: "hist-178",
    date: "2026-06-06",
    mood_label: "Focused",
    mood_category: "Calm",
    text: `<p>Wewnętrzna prezentacja w Kolibri o tym jak zmienił się design process w firmie przez ostatnie dwa lata — z moją perspektywą jako osoby która była tu od środka tych zmian. Przygotowując ją, uświadomiłam sobie że jesteśmy o lata świetlne od tego gdzie byliśmy. Zmiany są trudne do zobaczenia kiedy jesteś w środku.</p>`,
    created_at: "2026-06-06T15:00.000Z",
    updated_at: "2026-06-06T15:00:00.000Z",
  },
  {
    id: "hist-179",
    date: "2026-06-09",
    mood_label: "Content",
    mood_category: "Positive",
    text: `<p>Dzisiaj piszę ten wpis świadomie — mija dokładnie trzy lata od kiedy zaczęłam. Nie miałam planu, miałam tylko kartkę i polecenie terapeutki żeby pisać. Teraz mam 179 wpisów, które opisują osobę która przez trzy lata szukała swojego miejsca — i je znalazła. Nie jest to końcowy punkt, ale jest to dobre miejsce do oddechu. Do zobaczenia jutro.</p>`,
    created_at: "2026-06-09T21:00.000Z",
    updated_at: "2026-06-09T21:00:00.000Z",
  },
];
